site_name: Key Mapper Documentation
site_author: sds100
repo_url: https://github.com/sds100/KeyMapper
site_description: Documentation website for the Key Mapper Android app.
nav:
  - Home: index.md
  - Quick Start Guide: quick-start.md
  - FAQ: faq.md
  - User Guide:
      - Triggers: user-guide/triggers.md
      - Actions: user-guide/actions.md
      - Constraints: user-guide/constraints.md
      - ADB Permissions: user-guide/adb-permissions.md
      - Fingerprint Gestures (2.2.0+, Android 8.0+): user-guide/fingerprint-gestures.md
      - Back up and Restore (2.1.0+, Android 4.4+): user-guide/backup-restore.md
  - Contributing: contributing.md
  - Known Issues: known-issues.md

theme: 
  name: material
  palette:
    accent: red
  favicon: images/favicon.ico
  logo: images/logo.png
  custom_dir: docs/overrides
  features:
    - navigation.instant

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sds100/KeyMapper
    - icon: fdroid
      link: https://www.f-droid.org/en/packages/io.github.sds100.keymapper/
    - icon: fontawesome/brands/discord
      link: https://keymapper.club
    - icon: fontawesome/brands/google-play
      link: https://play.google.com/store/apps/developer?id=sds100
    - icon: fontawesome/solid/envelope
      link: mailto:developer.sds100@gmail.com
    - icon: kofi
      link: https://ko-fi.com/sethschroeder

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - toc:
      permalink: true

plugins:
  - redirects:
      redirect_maps:
        'redirects/trigger-by-intent.md': 'https://sds100.github.io/KeyMapper/user-guide/triggers/#trigger-by-intent-v230'
        'redirects/grant-write-secure-settings.md': 'https://sds100.github.io/KeyMapper/user-guide/adb-permissions/#write_secure_settings'
        'redirects/faq.md': 'https://sds100.github.io/KeyMapper/faq'
        'redirects/quick-start.md': 'https://sds100.github.io/KeyMapper/quick-start'
        'redirects/fingerprint-map-options.md': 'https://sds100.github.io/KeyMapper/user-guide/fingerprint-gestures'
        'redirects/constraints.md': 'https://sds100.github.io/KeyMapper/user-guide/constraints'
        'redirects/action.md': 'https://sds100.github.io/KeyMapper/user-guide/actions'
        'redirects/trigger.md': 'https://sds100.github.io/KeyMapper/user-guide/triggers'
        'redirects/trigger-options.md': 'https://sds100.github.io/KeyMapper/user-guide/triggers/#options'
  - search:
      lang:
        - en
